# Generated by Django 5.2.6 on 2025-10-01 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_profile_image"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Profile",
        ),
    ]
