# Generated by Django 5.2.6 on 2025-10-01 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(
                default="profile_pics/default_avatar.png", upload_to="profile_pics"
            ),
        ),
    ]
