# Generated by Django 5.2.6 on 2025-09-25 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="curiosity",
            name="picture",
            field=models.CharField(
                default="https://animalclinic.org/wp-content/uploads/2019/05/paw-placeholder.png",
                max_length=500,
            ),
        ),
        migrations.AlterField(
            model_name="curiosity",
            name="content",
            field=models.TextField(),
        ),
    ]
